steps:
- name: 'gcr.io/data-rivers/airflow'
  volumes:
    - name: 'vol1'
      path: '/persistent_volume'
  id: Install dataflow_utils
  entrypoint: python
  args:
    - '/workspace/dags/dependencies/dataflow_scripts/setup.py'
    - 'install'
- name: 'gcr.io/data-rivers/airflow'
  volumes:
    - name: 'vol1'
      path: '/persistent_volume'
  id: Install reqs + test
  entrypoint: /bin/sh
  args:
    - -c
    - 'pip install -r requirements.txt && pip install -r requirements-gcp.txt && pytest'
  env:
    - 'GCLOUD_PROJECT=data-rivers'
  volumes:
    - name: 'vol1'
      path: '/persistent_volume'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy if master
  entrypoint: bash
  args:
    - -c
    - 'if [ "$BRANCH_NAME" == "master" ]; then echo "$BRANCH_NAME" && make deploy;
        else echo "Working on $BRANCH_NAME"; fi'