steps:
- name: 'gcr.io/data-rivers/airflow'
  id: Install requirements
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install pytest && pip install -r requirements.txt && pip install -r requirements-gcp.txt && echo $PWD'
- name: 'gcr.io/data-rivers/airflow'
  id: Install dataflow_utils
  entrypoint: python
  args:
    - '/workspace/dags/dependencies/dataflow_scripts/setup.py install'
- name: 'gcr.io/data-rivers/airflow'
  id: Run tests
  entrypoint: python
  args:
    - -m
    - 'pytest'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  entrypoint: bash
  args:
    - -c
    - 'if [ "$BRANCH_NAME" == "master" ]; then echo "$BRANCH_NAME" && make deploy;
        else echo "Working on $BRANCH_NAME"; fi'